show databases;
use employee;

CREATE TABLE emp (
	EMPLOYEE_ID INT NOT NULL ,
	FIRST_NAME CHAR(45),
    LAST_NAME CHAR(45),
	SALARY INT NOT NULL,
    JOINING_DATE DATETIME,
	DEPARTMENT CHAR(45),
	primary key(EMPLOYEE_ID)
);

CREATE TABLE incentives(
	EMP_REF_ID INT NOT NULL,
    INC_DATE DATE,
    INC_AMOUNT INT NOT NULL,
    FOREIGN KEY (EMP_REF_ID)
		REFERENCES emp(EMPLOYEE_ID)
        ON DELETE CASCADE
);

INSERT INTO emp
	(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(1, 'John', 'Abraham', 1000000, '13-01-01 12.00.00', 'Banking');
INSERT INTO emp
	(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(2, 'Michael', 'Clarke', 800000, '13-01-01 12.00.00', 'Insurance');
INSERT INTO emp
	(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(3, 'Roy', 'Thomas', 700000, '13-02-01 12.00.00', 'Banking');
INSERT INTO emp
	(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(4, 'Tom', 'Jose', 600000, '13-02-01 12.00.00', 'Insurance');
INSERT INTO emp
	(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(5, 'Jerry', 'Pinto', 650000, '13-02-01 12.00.00', 'Insurance');
INSERT INTO emp
	(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(6, 'Philip', 'Mathew', 750000, '13-01-01 12.00.00', 'Services');
INSERT INTO emp
	(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(7, 'TestName1', '123', 650000, '13-01-01 12.00.00', 'Services');
INSERT INTO emp
	(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
		(8, 'TaestName2', 'Lname%', 600000, '13-02-01 12.00.00', 'Insurance');
        
INSERT INTO incentives
    (EMP_REF_ID,INC_DATE,INC_AMOUNT) VALUES
       (1,'13-02-01',5000);
INSERT INTO incentives
    (EMP_REF_ID,INC_DATE,INC_AMOUNT) VALUES
       (2,'13-02-01',3000);
INSERT INTO incentives
    (EMP_REF_ID,INC_DATE,INC_AMOUNT) VALUES
       (3,'13-02-01',4000);
INSERT INTO incentives
    (EMP_REF_ID,INC_DATE,INC_AMOUNT) VALUES
       (1,'13-01-01',4500);
INSERT INTO incentives
    (EMP_REF_ID,INC_DATE,INC_AMOUNT) VALUES
       (2,'13-01-01',3500);