use fifthproc;

CREATE TABLE EMP_DETAILS(
	EMP_IDNO INT NOT NULL,
    EMP_FNAME CHAR(45),
    EMP_LNAME CHAR(45),
    EMP_DEPT INT NOT NULL,
    EMP_SAL INT NOT NULL,
    PRIMARY KEY(EMP_IDNO)
);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (100,'Michaeeele','Rock',63,1000);

INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (127323,'Michale','Robbin',57,20990);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (526689,'Carlos','Snares',63,45455);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (843795,'Enric','Dosio',57,3030);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (328717,'Jhon','Snares',63,43000);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (444527,'Joseph','Donsi',47,30001);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (659831,'Zanifer','Emily',47,70000);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (847674,'Kuleswar','Sitaraman',57,100000);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (748681,'Henry','Gabriel',47,60000);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (555935,'Alex','Manuel',57,7000);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (539569,'George','Mardy',27,8999);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (733843,'Mario','Saule',63,9000);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (631548,'Alan','Snappy',27,89000);
INSERT INTO emp_details
	(EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
        (839139,'Maria','Foster',57,6700);