show databases;
use employeedetail;

CREATE TABLE empdet (
	EMPLOYEEID INT NOT NULL ,
	FIRSTNAME VARCHAR(20),
    LASTNAME CHAR(45),
	SALARY INT NOT NULL,
    JOININGDATE DATETIME,
	DEPARTMENT CHAR(12),
    GENDER VARCHAR(10),
	primary key(EMPLOYEEID)
);

CREATE TABLE projdet (
    PROJECTDETAILID INT NOT NULL,
	EMPLOYEEDETAILID INT NOT NULL ,
    PROJECTNAME CHAR(45),
    PRIMARY KEY(PROJECTDETAILID)
);

INSERT INTO empdet
	(EMPLOYEEID, FIRSTNAME, LASTNAME, SALARY, JOININGDATE, DEPARTMENT,GENDER) VALUES
		(1, 'Vikas', 'Ahlawat', 600000, '13-02-15 11.16.28.290', 'IT','Male');
INSERT INTO empdet
	(EMPLOYEEID, FIRSTNAME, LASTNAME, SALARY, JOININGDATE, DEPARTMENT,GENDER) VALUES
		(2, 'Nikita', 'Jain', 530000, '14-01-09 17.31.07.793', 'HR','Female');
INSERT INTO empdet
	(EMPLOYEEID, FIRSTNAME, LASTNAME, SALARY, JOININGDATE, DEPARTMENT,GENDER) VALUES
		(3, 'Ashish', 'Kumar', 1000000, '14-01-09 05.00.07.793', 'IT','Male');
INSERT INTO empdet
	(EMPLOYEEID, FIRSTNAME, LASTNAME, SALARY, JOININGDATE, DEPARTMENT,GENDER) VALUES
		(4, 'Nikhil', 'Sharma', 480000, '14-01-09 09.00.07.793', 'HR','Male');
INSERT INTO empdet
	(EMPLOYEEID, FIRSTNAME, LASTNAME, SALARY, JOININGDATE, DEPARTMENT,GENDER) VALUES
		(5, 'Anish', 'Kadian', 500000, '14-01-09 09.31.07.793', 'Payroll','Male');

/*****************************************************************************************/
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(1,1,'Task Track');
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(2,1,'CLP');
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(3,1,'Survey Management');
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(4,2,'HR Management');
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(5,3,'Task Track');
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(6,3,'GRS');
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(7,3,'DDS');
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(8,4,'HR Management');
INSERT INTO projdet
	(PROJECTDETAILID,EMPLOYEEDETAILID, PROJECTNAME) VALUES
		(9,6,'GL Management');

