use sales_man;
SELECT * FROM ORDERS WHERE PURCH_AMT > (SELECT AVG(PURCH_AMT) FROM ORDERS WHERE ORD_DATE ='2012-10-10');
SELECT COUNT(CUST_NAME) FROM CUSTOMERS WHERE GRADE > (SELECT AVG(GRADE) FROM CUSTOMERS WHERE CITY='New York');
SELECT NAME,SALESMAN_ID FROM SALESMAN S WHERE 1 < ANY (SELECT COUNT(SALESMAN_ID)  FROM CUSTOMERS WHERE S.SALESMAN_ID=SALESMAN_ID);
#FROM CUSTOMERS GROUP BY SALESMAN_ID HAVING COUNT(SALESMAN_ID)>1 
SELECT * FROM CUSTOMERS WHERE 1 <=  (SELECT COUNT(CITY) FROM CUSTOMERS WHERE CITY='London'); 
SELECT * FROM SALESMAN S WHERE 1 < (SELECT COUNT(CUST_NAME) FROM CUSTOMERS C WHERE 1 < (SELECT COUNT(ORD_NO) FROM ORDERS WHERE C.SALESMAN_ID =SALESMAN_ID) AND C.SALESMAN_ID=S.SALESMAN_ID);
SELECT * FROM SALESMAN S WHERE CITY IN (SELECT CITY FROM CUSTOMERS WHERE S.CITY = CITY);
SELECT * FROM SALESMAN A WHERE A.CITY IN (SELECT CITY FROM CUSTOMERS);
SELECT * FROM CUSTOMERS WHERE GRADE > ANY (SELECT GRADE FROM CUSTOMERS WHERE CITY<'New York');
SELECT * FROM ORDERS WHERE PURCH_AMT > ANY (SELECT PURCH_AMT FROM CUSTOMERS WHERE ORD_DATE = '2012-09-10');
SELECT * FROM CUSTOMERS WHERE GRADE > ALL (SELECT GRADE FROM CUSTOMERS WHERE CITY='New York');
