use salesman;
SELECT * FROM salesman;
SELECT "This is SQL Exercise, Practice and Solution" AS 'DISPLAY';
SELECT 10,20,30;
SELECT 500+90;
SELECT 2*4-8*9/2+100;
SELECT NAME,COMMISSION FROM SALESMAN;
SELECT DISTINCT (SALESMAN_ID) FROM ORDERS;
SELECT NAME,CITY FROM SALESMAN WHERE CITY="PARIS";
SELECT * FROM CUSTOMERS WHERE GRADE=200;
SELECT ORD_NO,ORD_DATE,PURCH_AMT FROM ORDERS WHERE SALESMAN_ID=5001;
SELECT SUBJECT,WINNER,COUNTRY,CATEGORY FROM NOBEL_WIN WHERE YEAR=1970;
SELECT WINNER FROM NOBEL_WIN WHERE YEAR=1971 AND SUBJECT='LITERATURE';
SELECT YEAR,SUBJECT FROM NOBEL_WIN WHERE WINNER='DENNIS GABOR';
SELECT WINNER FROM NOBEL_WIN WHERE SUBJECT='PHYSICS' AND YEAR>=1950;
SELECT * FROM NOBEL_WIN WHERE SUBJECT='CHEMISTRY' AND YEAR BETWEEN 1965 AND 1975;
SELECT * FROM NOBEL_WIN WHERE CATEGORY='PRIME MINISTER' AND YEAR>1972;
SELECT * FROM NOBEL_WIN WHERE WINNER LIKE 'LOUIS%';
SELECT * FROM NOBEL_WIN WHERE (SUBJECT='PHYSICS' AND YEAR=1970) OR (SUBJECT='ECONOMICS' AND YEAR=1971);
SELECT * FROM nobel_win WHERE year=1970 AND subject NOT IN('Physiology','Economics');
SELECT *  FROM NOBEL_WIN WINNER WHERE (SUBJECT='PHYSIOLOGY' AND YEAR<1971) OR (SUBJECT='PEACE' AND YEAR>=1974);
SELECT * FROM NOBEL_WIN WHERE WINNER LIKE 'Johannes Georg Bednorz';
SELECT * FROM NOBEL_WIN WHERE WINNER NOT LIKE 'P%' ORDER BY YEAR DESC,WINNER;
SELECT * FROM NOBEL_WIN WHERE YEAR=1970 ORDER BY SUBJECT DESC,WINNER;
SELECT * FROM ITEM_MAST WHERE PRO_PRICE BETWEEN 200 AND 600;
SELECT AVG(PRO_PRICE) FROM item_mast WHERE PRO_COM=16;
SELECT pro_name as "Item Name", pro_price AS "Price in Rs." FROM item_mast;
SELECT pro_name, pro_price FROM item_mast WHERE pro_price >= 250 ORDER BY pro_price DESC, pro_name;
SELECT AVG(pro_price), pro_com FROM item_mast GROUP BY pro_com;
SELECT PRO_NAME,PRO_PRICE FROM ITEM_MAST WHERE PRO_PRICE=(SELECT MIN(PRO_PRICE) FROM ITEM_MAST);
SELECT DISTINCT(EMP_LNAME) FROM emp_details;
SELECT * FROM EMP_DETAILS WHERE EMP_LNAME IN ('SNARES');
SELECT * FROM EMP_DETAILS WHERE EMP_DEPT=57;






