use fifthproc;
# DROP PROCEDURE IF EXISTS NAME;
DELIMITER $$

CREATE  FUNCTION employer_details_func()
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
	DECLARE EMP_NAME VARCHAR(20) DEFAULT 0;
	SELECT EMP_FNAME INTO EMP_NAME FROM EMP_DETAILS WHERE EMP_IDNO = 100;
	RETURN emp_name;
END$$
 DELIMITER ;
DELIMITER $$
CREATE PROCEDURE update_emp(IN emp_name CHAR(20))
BEGIN
   SET SQL_SAFE_UPDATES=0;
  UPDATE EMP_DETAILS SET EMP_SAL = (EMP_SAL+(0.05*EMP_SAL)) WHERE EMP_FNAME=EMP_NAME;
  SELECT * FROM EMP_DETAILS WHERE  EMP_FNAME=EMP_NAME;
END $$
DELIMITER ; 

DELIMITER &&

CREATE PROCEDURE SUM_N(INOUT N INT)
BEGIN
     SELECT ((N*(N+1))/2) INTO N ;
END &&
DELIMITER ;
DELIMITER $$
CREATE PROCEDURE CHANGE_NAME(IN EMP_ID INT, IN E_NAME CHAR(20))
BEGIN
	UPDATE EMP_DETAILS SET EMP_FNAME=E_NAME WHERE EMP_IDNO=EMP_ID;
    SELECT * FROM EMP_DETAILS WHERE  EMP_FNAME=E_NAME;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE DELETE_ID(IN EMP_ID INT)
BEGIN
DELETE FROM EMP_DETAILS WHERE EMP_IDNO=EMP_ID;
SELECT * FROM EMP_DETAILS;
END $$
DELIMITER ;

DELIMITER &&
CREATE PROCEDURE SWAP(IN N INT,IN M INT)
BEGIN
DECLARE TEMP INT;
SET SQL_SAFE_UPDATES=0;
 /*UPDATE EMP_DETAILS 
 SET EMP_SAL=EMP_IDNO+EMP_SAL,
 EMP_IDNO=EMP_SAL-EMP_IDNO,
 EMP_SAL=EMP_SAL-EMP_IDNO;
 SELECT * FROM EMP_DETAILS;*/
 #SET N=10;
 #SET M=20;
 #SELECT N,M AS ' ';
 SET TEMP=N;
 SET N=M;
 SET M=TEMP;
 SELECT N,M ;
END &&
 
DELIMITER ;  
DELIMITER &&

CREATE PROCEDURE SAL_DISP()
BEGIN
SELECT EMP_FNAME,EMP_LNAME,EMP_SAL FROM EMP_DETAILS WHERE EMP_SAL > (SELECT AVG(EMP_SAL) AS AVG_SAL FROM EMP_DETAILS);
END&&

DELIMITER ;
DELIMITER $$

CREATE PROCEDURE ADD_ENTRY(IN EMP_ID INT, IN F_NAME CHAR(20),IN L_NAME CHAR(20), IN DEPT INT,IN SAL INT)
BEGIN
SET sql_mode = "";
CREATE TABLE EMPLOYEE(
	EMP_IDNO INT NOT NULL,
    EMP_FNAME CHAR(45),
    EMP_LNAME CHAR(45),
    EMP_DEPT INT NOT NULL,
    EMP_SAL INT NOT NULL,
    PRIMARY KEY(EMP_IDNO)
);
INSERT INTO EMPLOYEE (EMP_IDNO,EMP_FNAME,EMP_LNAME,EMP_DEPT,EMP_SAL) VALUES
(EMP_ID,F_NAME,L_NAME,DEPT,SAL);
SELECT * FROM EMPLOYEE;
END $$
DELIMITER ;

CALL update_emp('George');
SET@M=3;
CALL SUM_N(@M);
SELECT @M;
CALL CHANGE_NAME(100,'Rose'); 
CALL DELETE_ID(631548);
CALL SWAP(10,20);
CALL SAL_DISP();
CALL ADD_ENTRY(109,'DON','BOSCO',45,15500);



