use cursors_emp;

#ALTER TABLE emp
 # DROP COLUMN emp_dept;
DROP TABLE IF EXISTS OUTPUT_EMP;  
DELIMITER $$
CREATE PROCEDURE DISP_DET()
BEGIN
DECLARE ID INT DEFAULT 0;
DECLARE FINISHED INT DEFAULT 0;
DECLARE NAM CHAR(20) DEFAULT "";
DECLARE SAL INT DEFAULT 0;
DECLARE CUREMP CURSOR FOR SELECT * FROM EMP;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
CREATE TEMPORARY table OUTPUT_EMP (Emp_Id int ,Emp_name char(20),Emp_sal int);

OPEN CUREMP;
GETREC: LOOP
        FETCH CUREMP INTO ID,NAM,SAL;
        IF FINISHED = 1 THEN LEAVE GETREC;
        END IF;
        INSERT INTO OUTPUT_EMP (EMP_ID,EMP_NAME,EMP_SAL) VALUES (ID,NAM,SAL);
        END LOOP GETREC;
        CLOSE CUREMP;
        SELECT * FROM OUTPUT_EMP;
END $$

DELIMITER ;

DELIMITER $$
CREATE PROCEDURE update_emp()
BEGIN
DECLARE SAL INT DEFAULT 0;
DECLARE FINISHED INT DEFAULT 0;
DECLARE CUREMP CURSOR FOR SELECT emp_sal FROM EMP WHERE EMP_DEPT=17;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
   SET SQL_SAFE_UPDATES=0;
  OPEN CUREMP;
GETREC: LOOP
        FETCH CUREMP INTO SAL;
        IF FINISHED = 1 THEN LEAVE GETREC;
        END IF;
        IF SAL< 90000 THEN UPDATE EMP SET EMP_SAL = (EMP_SAL+(0.12*EMP_SAL)) ; ELSE UPDATE EMP SET EMP_SAL = (EMP_SAL+(0.20*EMP_SAL));END IF;
        END LOOP GETREC;
        CLOSE CUREMP;
        SELECT * FROM EMP;
END $$
DELIMITER ;

/*DELIMITER $$
CREATE PROCEDURE updat_emp()
BEGIN
DECLARE SAL INT DEFAULT 0;
DECLARE INC_AMT DECIMAL DEFAULT 0;
DECLARE FINISHED INT DEFAULT 0;
DECLARE DEP INT DEFAULT 0;
DECLARE CUREMP CURSOR FOR SELECT EMP_dept,emp_sal FROM EMP WHERE EMP_DEPT=17 FOR UPDATE;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
   SET SQL_SAFE_UPDATES=0;
  OPEN CUREMP;
GETREC: LOOP
        FETCH CUREMP INTO DEP,SAL;
        IF FINISHED = 1 THEN LEAVE GETREC;
        END IF;
        IF SAL< 90000 THEN SET INC_AMT := 0.20 ; ELSE  SET INC_AMT = 0.12;END IF;
        UPDATE EMP SET EMP_SAL = (EMP_SAL+(INC_AMT*EMP_SAL)) WHERE CURRENT OF CUREMP;
        END LOOP GETREC;
        CLOSE CUREMP;
        SELECT * FROM EMP;
END $$
DELIMITER ;*/

DELIMITER $$
CREATE PROCEDURE IMPLI()
BEGIN
DECLARE CUREMP CURSOR FOR SELECT * FROM EMP;
END $$
DELIMITER ;

CALL DISP_DET();
CALL UPDate_emp();


