use employeedetail;
#SELECT FIRSTNAME,PROJECTNAME FROM empdet,projdet WHERE EMPDET.EMPLOYEEID=PROJDET.EMPLOYEEDETAILID ORDER BY FIRSTNAME ; 
SELECT FIRSTNAME,PROJECTNAME FROM EMPDET A INNER JOIN projdet B ON A.EMPLOYEEID=B.EMPLOYEEDETAILID ORDER BY FIRSTNAME; 
SELECT FIRSTNAME,PROJECTNAME FROM EMPDET A LEFT OUTER JOIN projdet B ON A.EMPLOYEEID=B.EMPLOYEEDETAILID ORDER BY FIRSTNAME; 
SELECT PROJECTNAME FROM PROJDET A RIGHT OUTER JOIN EMPDET B ON B.EMPLOYEEID=A.EMPLOYEEDETAILID ORDER BY FIRSTNAME;
SELECT FIRSTNAME FROM EMPDET A LEFT JOIN projdet B ON A.EMPLOYEEID=B.EMPLOYEEDETAILID UNION SELECT FIRSTNAME,PROJECTNAME FROM EMPDET A RIGHT JOIN projdet B ON A.EMPLOYEEID=B.EMPLOYEEDETAILID ORDER BY FIRSTNAME;
SELECT PROJECTNAME FROM EMPDET A LEFT OUTER  JOIN projdet B ON A.EMPLOYEEID=B.EMPLOYEEDETAILID WHERE PROJECTNAME IS NULL ; 
SELECT FIRSTNAME ,PROJECTNAME FROM EMPDET A RIGHT OUTER  JOIN projdet B ON A.EMPLOYEEID=B.EMPLOYEEDETAILID WHERE FIRSTNAME IS NULL ; 
SELECT DISTINCT FIRSTNAME FROM EMPDET A LEFT OUTER  JOIN projdet B ON A.EMPLOYEEID=B.EMPLOYEEDETAILID WHERE EMPLOYEEID IN (SELECT  EMPLOYEEDETAILID FROM PROJDET GROUP BY EMPLOYEEDETAILID HAVING COUNT(EMPLOYEEDETAILID)>1)  ; 
SELECT DISTINCT PROJECTNAME FROM EMPDET A INNER  JOIN projdet B ON A.EMPLOYEEID=B.EMPLOYEEDETAILID WHERE PROJECTNAME IN (SELECT  PROJECTNAME FROM PROJDET GROUP BY PROJECTNAME HAVING COUNT(PROJECTNAME)>1)  ;

use salesman;
SELECT NAME,CUST_NAME,C.CITY FROM SALESMAN S INNER JOIN CUSTOMERS C ON S.CITY=C.CITY;
SELECT ORD_NO,PURCH_AMT,CUST_NAME,CITY FROM CUSTOMERS C LEFT JOIN ORDERS O ON O.CUSTOMER_ID=C.CUSTOMER_ID  WHERE PURCH_AMT BETWEEN 500 AND 2000;
SELECT NAME,CUST_NAME FROM SALESMAN S LEFT JOIN CUSTOMERS C ON C.SALESMAN_ID=S.SALESMAN_ID;
SELECT CUST_NAME FROM CUSTOMERS C INNER JOIN SALESMAN S ON C.SALESMAN_ID=S.SALESMAN_ID WHERE COMMISSION > 0.12;
SELECT CUST_NAME FROM SALESMAN S INNER JOIN CUSTOMERS C ON C.SALESMAN_ID=S.SALESMAN_ID WHERE COMMISSION > 0.12 AND S.CITY!=C.CITY ;
SELECT ORD_NO,ORD_DATE,PURCH_AMT,CUST_NAME,NAME,COMMISSION FROM ORDERS O INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID=C.CUSTOMER_ID INNER JOIN SALESMAN S ON C.SALESMAN_ID=S.SALESMAN_ID;
SELECT DISTINCT ORD_NO,ORD_DATE,PURCH_AMT,CUST_NAME,NAME,COMMISSION FROM ORDERS O INNER JOIN CUSTOMERS C ON O.CUSTOMER_ID=C.CUSTOMER_ID INNER JOIN SALESMAN S ON C.SALESMAN_ID=S.SALESMAN_ID;
SELECT CUST_NAME FROM CUSTOMERS C WHERE C.SALESMAN_ID IS NOT NULL ORDER BY C.CUST_NAME ASC;
SELECT CUST_NAME FROM CUSTOMERS C WHERE C.GRADE<300 AND C.SALESMAN_ID IS NOT NULL ORDER BY C.CUST_NAME ASC;
SELECT a.cust_name,a.city, b.ord_no, b.ord_date,b.purch_amt AS "Order Amount", c.name,c.commission FROM customerS a LEFT OUTER JOIN orders b ON a.customer_id=b.customer_id LEFT OUTER JOIN salesman c ON c.salesman_id=b.salesman_id;
SELECT a.cust_name,a.city,a.grade, b.name AS "Salesman", b.city FROM customers a RIGHT OUTER JOIN salesman b ON b.salesman_id=a.salesman_id ORDER BY b.salesman_id;



